import board
import usb_hid
from adafruit_debouncer import Debouncer
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
import digitalio
import time

#
# Auto-generated by tools/streamlit_macropad_ui/app.py
# Multi-tap text macropad (3 keys x 3 tap-counts = 9 outputs)
#
# - Tap a key 1/2/3 times within TAP_WINDOW_S -> sends different text.
# - If multiple keys are pressed at the same time, the first key pressed wins;
#   other keys are ignored until the active key is fully released and its tap
#   sequence is committed.
#



# ----- Hardware pins -----
PINS = [board.GP27, board.GP26, board.GP15]

# ----- Timing tuning -----
TAP_WINDOW_S = 1.0
POLL_S = 0.005

# ----- Text outputs -----
TEXTS = [['Hungry', 'Thirsty', 'Itch'], ['Choking', 'Bathroom', 'Painful'], ['Help', 'Adjust me', 'Cold/Hot']]

# ----- Formatting -----
PREFIX = ''
SUFFIX = ''
ADD_NEWLINE = False

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayoutUS(kbd)

pins = [digitalio.DigitalInOut(i) for i in PINS]
for pin in pins:
    pin.direction = digitalio.Direction.INPUT
    pin.pull = digitalio.Pull.UP
switches = [Debouncer(i) for i in pins]


def _format_text(s: str) -> str:
    out = f"{PREFIX}{s}{SUFFIX}"
    if ADD_NEWLINE:
        out += "\n"
    return out


active_key = None
tap_count = 0
last_tap_time = 0.0
waiting_for_release = False

while True:
    now = time.monotonic()
    for sw in switches:
        sw.update()

    if active_key is None:
        for idx, sw in enumerate(switches):
            if sw.fell:
                active_key = idx
                tap_count = 1
                last_tap_time = now
                waiting_for_release = True
                break
    else:
        sw = switches[active_key]
        if waiting_for_release:
            if sw.rose:
                waiting_for_release = False
        else:
            if sw.fell:
                tap_count += 1
                if tap_count > 3:
                    tap_count = 3
                last_tap_time = now
                waiting_for_release = True

            if (now - last_tap_time) > TAP_WINDOW_S and (not waiting_for_release):
                text = TEXTS[active_key][tap_count - 1]
                layout.write(_format_text(text))
                active_key = None
                tap_count = 0
                last_tap_time = 0.0
                waiting_for_release = False

    time.sleep(POLL_S)