import json
from dataclasses import dataclass, asdict

import streamlit as st


@dataclass
class Config:
    # 3 keys x (1..3 taps)
    texts: list[list[str]]
    prefix: str = ""
    suffix: str = ""
    add_newline: bool = False
    tap_window_s: float = 1.0
    poll_s: float = 0.005
    # v1 boarrd -> GP27/GP26/GP15 pins, v2 board -> GP9/GP10/GP11 pins
    hardware: str = "v1"
    v2_drive_gp29_low: bool = False


DEFAULT = Config(
    texts=[
        ["Hungry ", "Thirsty ", "Itch "],
        ["Choking ", "Bathroom ", "Painful "],
        ["Help ", "Adjust me ", "Cold/Hot "],
    ]
)



##the format fot the code file output at the bottom of the website ###########################################################
FIRMWARE_TEMPLATE = """import board
import usb_hid
from adafruit_debouncer import Debouncer
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
import digitalio
import time

#
# Auto-generated by tools/streamlit_macropad_ui/app.py
# Multi-tap text macropad (3 keys x 3 tap-counts = 9 outputs)
#
# - Tap a key 1/2/3 times within TAP_WINDOW_S -> sends different text.
# - If multiple keys are pressed at the same time, the first key pressed wins;
#   other keys are ignored until the active key is fully released and its tap
#   sequence is committed.
#

{v2_gp29_setup}

# ----- Hardware pins -----
PINS = {pins}

# ----- Timing tuning -----
TAP_WINDOW_S = {tap_window_s}
POLL_S = {poll_s}

# ----- Text outputs -----
TEXTS = {texts}

# ----- Formatting -----
PREFIX = {prefix}
SUFFIX = {suffix}
ADD_NEWLINE = {add_newline}

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayoutUS(kbd)

pins = [digitalio.DigitalInOut(i) for i in PINS]
for pin in pins:
    pin.direction = digitalio.Direction.INPUT
    pin.pull = digitalio.Pull.UP
switches = [Debouncer(i) for i in pins]


def _format_text(s: str) -> str:
    out = f"{{PREFIX}}{{s}}{{SUFFIX}}"
    if ADD_NEWLINE:
        out += "\\n"
    return out


active_key = None
tap_count = 0
last_tap_time = 0.0
waiting_for_release = False

while True:
    now = time.monotonic()
    for sw in switches:
        sw.update()

    if active_key is None:
        for idx, sw in enumerate(switches):
            if sw.fell:
                active_key = idx
                tap_count = 1
                last_tap_time = now
                waiting_for_release = True
                break
    else:
        sw = switches[active_key]
        if waiting_for_release:
            if sw.rose:
                waiting_for_release = False
        else:
            if sw.fell:
                tap_count += 1
                if tap_count > 3:
                    tap_count = 3
                last_tap_time = now
                waiting_for_release = True

            if (now - last_tap_time) > TAP_WINDOW_S and (not waiting_for_release):
                text = TEXTS[active_key][tap_count - 1]
                layout.write(_format_text(text))
                active_key = None
                tap_count = 0
                last_tap_time = 0.0
                waiting_for_release = False

    time.sleep(POLL_S)
"""


def pins_for(hardware: str) -> str:
    if hardware == "v2":
        return "[board.GP9, board.GP10, board.GP11]"
    return "[board.GP27, board.GP26, board.GP15]"


def render_firmware(cfg: Config) -> str:
    v2_gp29_setup = ""
    if cfg.hardware == "v2" and cfg.v2_drive_gp29_low:
        v2_gp29_setup = "\n".join(
            [
                "# Additional setup for some V2 boards (required based on schematic)",
                "pin4 = digitalio.DigitalInOut(board.GP29)",
                "pin4.direction = digitalio.Direction.OUTPUT",
                "pin4.value = False  # Set GP29 pin to low",
                "",
            ]
        )

    return FIRMWARE_TEMPLATE.format(
        v2_gp29_setup=v2_gp29_setup,
        pins=pins_for(cfg.hardware),
        tap_window_s=cfg.tap_window_s,
        poll_s=cfg.poll_s,
        texts=repr(cfg.texts),
        prefix=repr(cfg.prefix),
        suffix=repr(cfg.suffix),
        add_newline=repr(cfg.add_newline),
    )


def format_preview(cfg: Config, key_index: int, taps: int) -> str:
    s = cfg.texts[key_index][taps - 1]
    out = f"{cfg.prefix}{s}{cfg.suffix}"
    if cfg.add_newline:
        out += "\n"
    return out

############ START OF STREAMLIT APP ###########################################################
st.set_page_config(page_title="Macropad Multi-Tap Formatter", layout="wide")
st.title("Macropad Multi-Tap Formatter")

st.caption(
    "Edit the 9 outputs (3 keys X 3 taps) and formatting, then export a CircuitPython `code.py`."
)

if "cfg" not in st.session_state:
    st.session_state.cfg = asdict(DEFAULT)


with st.sidebar:
    st.header("Hardware")
    hardware = st.radio("Board version", options=["v1", "v2"], index=0 if st.session_state.cfg["hardware"] == "v1" else 1) # Default is alwys v1
    st.session_state.cfg["hardware"] = hardware
    st.session_state.cfg["v2_drive_gp29_low"] = st.checkbox(
        "V2: drive GP29 low (if required)",
        value=bool(st.session_state.cfg.get("v2_drive_gp29_low", False)),
        disabled=(hardware != "v2"),
    )

    st.header("Multi-tap timing") #timing things for the macropad
    st.session_state.cfg["tap_window_s"] = float(
        st.slider("Tap window (seconds)", min_value=0.2, max_value=2.0, value=float(st.session_state.cfg["tap_window_s"]), step=0.05)
    )
    #polling delay for the pad
    st.session_state.cfg["poll_s"] = float(
        st.slider("Poll delay (seconds)", min_value=0.0, max_value=0.05, value=float(st.session_state.cfg["poll_s"]), step=0.001)
    )

    st.divider()
    st.download_button(
        "Download config.json",
        data=json.dumps(st.session_state.cfg, indent=2),
        file_name="macropad_config.json",
        mime="application/json",
        use_container_width=True,
    )


st.subheader("Key outputs (Input texts in the box)")
cols = st.columns(3)
for key_idx in range(3):
    with cols[key_idx]:
        st.markdown(f"**Key {key_idx + 1}**")
        for taps in (1, 2, 3):
            # Read current value from session state (not from cfg, bc hasn't been updated yet)
            current_value = st.session_state.cfg["texts"][key_idx][taps - 1]
            new_value = st.text_area(
                f"{taps} tap(s)",
                value=current_value,
                height=72,
                key=f"k{key_idx}_t{taps}",
            )
            # Write each text area's value back into session state immediately
            st.session_state.cfg["texts"][key_idx][taps - 1] = new_value

# Now build cfg from the fully-updated session state
cfg = Config(**st.session_state.cfg)

st.divider()
st.subheader("Preview")
preview_cols = st.columns(3)
for key_idx in range(3):
    with preview_cols[key_idx]:
        st.markdown(f"**Key {key_idx + 1}**")
        for taps in (1, 2, 3):
            st.code(format_preview(cfg, key_idx, taps))


st.divider()
st.subheader("Export CircuitPython firmware")

firmware = render_firmware(cfg)
st.download_button(
    "Download code.py",
    data=firmware,
    file_name="code.py",
    mime="text/x-python",
    use_container_width=True,
)
st.text_area("Generated `code.py` (Copy)", value=firmware, height=360)  # work later to add a button to copy the code to the clipboard aft tuition